### ISSUE TITLE
idea 2024.2版本中无效

### ISSUE THREAD

**Issue by bestv5** [JAgentSphere/bytebuddy-agent-demo#11]
插件版本 [2024.2.6-241](https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/579101)

该插件在idea 2024.1版本中可以配置使用，但到了idea 2024.2版本中，还是弹窗了。

**Comment by AkazaAkaria** [comment]
你是怎么配置的呢,可以发一下你的配置吗

**Comment by bestv5** [comment]
> 你是怎么配置的呢,可以发一下你的配置吗

-Xms1G

-Xmx2G

-XX:ReservedCodeCacheSize=512m

-XX:+UseG1GC

-XX:SoftRefLRUPolicyMSPerMB=50

-XX:CICompilerCount=2

-XX:+HeapDumpOnOutOfMemoryError

-XX:-OmitStackTraceInFastThrow

-XX:CompileCommand=exclude,com/intellij/openapi/vfs/impl/FilePartNodeRoot,trieDescend

-ea

-Dsun.io.useCanonCaches=false

-Dsun.io.useCanonPrefixCache=false

-Djdk.http.auth.tunneling.disabledSchemes=""

-Djdk.attach.allowAttachSelf=true

-Djdk.module.illegalAccess.silent=true

-Dkotlinx.coroutines.debug=off

-Dide.no.platform.update=false

-Djava.net.preferIPv4Stack=true

-Didea.config.path=D:\\tools\\JetbrainsApp\\IDEA-U\\UserConfig\\config-2024.2

-Didea.plugins.path=D:\\tools\\JetbrainsApp\\IDEA-U\\UserConfig\\plugins-2024.2

-Didea.system.path=D:\\tools\\JetbrainsApp\\IDEA-U\\UserConfig\\system

-Didea.log.path=D:\\tools\\JetbrainsApp\\IDEA-U\\UserConfig\\log

-Dfile.encoding=UTF-8

-Dsplash=true



--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED

--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED

-javaagent:D:\tools\JetbrainsApp\ActivateTools\rainbow-brackets-cracked.jar

-javaagent:D:\tools\JetbrainsApp\ActivateTools\jetbra-240218\ja-netfilter.jar=jetbrains


config plugins目录和老版本隔离开了，system log和老版本共用。
idea 2024.1.4版本中使用的BR插件版本是 2024.2.4-241

**Comment by AkazaAkaria** [comment]
可以 带上截图吗,需要改哪里的文件,或者怎么联系你,请附带联系方式

**Comment by ReaJason** [comment]
先用这个顶一顶，https://t.me/nice2alive/39

**Comment by Muscleape** [comment]
> 先用这个顶一顶，https://t.me/c/1745119691/3434

这个消息看不了呢，提示不是成员，不能看

**Comment by ReaJason** [comment]
> 这个消息看不了呢，提示不是成员，不能看

更新了

**Comment by Muscleape** [comment]
> > > 先用这个顶一顶，https://t.me/c/1745119691/3434
> > 
> > 这个消息看不了呢，提示不是成员，不能看
> 
> 更新了

还是不行呢
![image](https://github.com/user-attachments/assets/91c423b1-55e3-4d02-9dc5-95b99489e228)

**Comment by ReaJason** [comment]
https://t.me/nice2alive

**Comment by AkazaAkaria** [comment]
![Clip_2024-08-14_20-37-05](https://github.com/user-attachments/assets/341330d5-3ff3-4d68-b265-9c65b2107f55)
提示这个
可以发一个详细的教程文档吗

**Comment by AkazaAkaria** [comment]
可以发一个详细的教程文档吗

**Comment by bestv5** [comment]
是不是可以众筹一个正版licence，本地激活使用😂





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2024年08月14日 08:57:15
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [JAgentSphere/bytebuddy-agent-demo] idea 2024.2版本中无效 (Issue #11)

https://t.me/nice2alive
