### ISSUE TITLE
更新至 rainbow-brackets 2024.2.6后无法使用

### ISSUE THREAD

**Issue by cacuts-c** [JAgentSphere/bytebuddy-agent-demo#12]
![image](https://github.com/user-attachments/assets/0e84f63a-2807-497a-a1b2-9b04cb1bb1ce)

**Comment by ReaJason** [comment]
确实，我刚更新了也这样了

**Comment by ReaJason** [comment]
定向爆破了一下 https://t.me/nice2alive/39

**Comment by bestv5** [comment]
下载不了，麻烦上传一下呗





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2024年08月14日 08:47:21
***@***.***>
***@***.***>
主　题：Re: [JAgentSphere/bytebuddy-agent-demo] 更新至 rainbow-brackets 2024.2.6后无法使用 (Issue #12)

定向爆破了一下 https://t.me/nice2alive/39
