### ISSUE TITLE
在vmoptions最后加了两行代码后连IDEA都无法启动

### ISSUE THREAD

**Issue by cimmu** [JAgentSphere/bytebuddy-agent-demo#3]
如标题，把两个jar准备好，修改vmoptions后想重启IDEA发现启动都启动不了

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/92285183/909376e4-3a00-463a-9228-7c9d84e7e1e3)

**Comment by ReaJason** [comment]
试试在命令行启动试试，然后看报错

https://intellij-support.jetbrains.com/hc/en-us/articles/360011901879-How-to-start-IDE-from-the-command-line#h_7bab70ec-bb3a-48c2-b8b8-993ea6abaffd

**Comment by cimmu** [comment]
感谢回复，经过调整现在IDEA是可以启动的了，但是插件那边是失效的。

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/92285183/a8b713fc-78c3-4744-830b-332c46d7048a)

options配置netfilter是放在后面的：

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/92285183/71af0c4f-ac12-4f8e-9b5d-36b3dd684f02)

**Comment by ReaJason** [comment]
你是用的最新的这个不，https://github.com/JAgentSphere/bytebuddy-agent-demo/releases/tag/2024.2.3 ，感觉这个不太可能，我也是这个版本

**Comment by gimgoo** [comment]
确实不行，大佬，开始我以为Windows跟mac可能不一样，但我后来又用mac试了一下，同样是检测到ja-netfilter不给用

![](
![image](http://p0.meituan.net/csc/c41d7d1414ee9c748939a0d0d1cc47be14854.png)
)

可能你在之前能破解，后来的破解不了了

**Comment by gimgoo** [comment]
我在mac上，用的就是这个最新的https://github.com/JAgentSphere/bytebuddy-agent-demo/releases/tag/2024.2.3 。 

IDEA也是2024.1的rainbow版本是2024.2.3-241。用了跟楼主一样，也是没效果的，一样提示存在ja-nofilter无法激活。可能大佬只是运气好刚好碰上了给你激活了

**Comment by ReaJason** [comment]
试试新的 https://github.com/JAgentSphere/bytebuddy-agent-demo/releases/tag/2024.2.4

**Comment by xb12369** [comment]
# 局破不了了

- 1、我用最新版本的提示我：there is no valid license in your account

![there is no valid license in your account](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/9302372/b19595b4-5ecb-48b7-a641-25daece936c1)

**Comment by xb12369** [comment]
- 2、低版本【[rainbow-brackets-2024.2.1](https://github.com/JAgentSphere/bytebuddy-agent-demo/releases/tag/rainbow-brackets-2024.2.1)】的又提示我这个：you are using ja-netfilter to crack the IDE

![you are using ja-netfilter to crack the IDE](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/9302372/dc896c78-2771-43a3-91b9-afef4dc78d99)
