### ISSUE TITLE
最近插件版本无法使用

### ISSUE THREAD

**Issue by hcliu987** [JAgentSphere/bytebuddy-agent-demo#4]
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/52879991/76124c76-acbd-4c8b-b936-bac75cbbe55a)
找不到相关提示的红色关键字。无法进行破解处理

**Comment by ReaJason** [comment]
试试新的 https://github.com/JAgentSphere/bytebuddy-agent-demo/releases/tag/2024.2.4

**Comment by gimgoo** [comment]
刚下载试了，确实不行

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/31849284/968de195-a357-4dfd-81e9-fe13d6270b3b)

**Comment by ReaJason** [comment]
你点一下帮助，编辑自定义的 VM options，我看一下
![CleanShot 2024-06-01 at 19 52 32](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/48389642/f8b33c86-7207-46c4-85e3-4466dd4432df)

**Comment by gimgoo** [comment]
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/31849284/183a2a25-7d45-4996-a693-2702f5ea5fd0)

**Comment by ReaJason** [comment]
执行一下命令看一下文件是不是损坏了，预期的 md5 是 14d86ee4893ebbae1b3d4e430a0b15be
```
md5 /Users/william/Documents/rainbow/rainbow-brackets-cracked.jar
```

**Comment by ReaJason** [comment]
如果文件正常的话，试试用一下我的 vmoptions 配置，你就修改最下面两行用你的文件所在地址
```
-Xms128m
-Xmx2304m
-XX:ReservedCodeCacheSize=512m
-XX:+IgnoreUnrecognizedVMOptions
-XX:+UseG1GC
-XX:SoftRefLRUPolicyMSPerMB=50
-XX:CICompilerCount=2
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-ea
-Dsun.io.useCanonCaches=false
-Djdk.http.auth.tunneling.disabledSchemes=""
-Djdk.attach.allowAttachSelf=true
-Djdk.module.illegalAccess.silent=true
-Dkotlinx.coroutines.debug=off
-XX:ErrorFile=$USER_HOME/java_error_in_idea_%p.log
-XX:HeapDumpPath=$USER_HOME/java_error_in_idea.hprof

--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED
-javaagent:/Users/reajason/IdeaProjects/bytebuddy-agent-demo/build/libs/rainbow-brackets-cracked.jar
-javaagent:/Users/reajason/ReaJason/jetbra/ja-netfilter.jar=jetbrains

```

**Comment by gimgoo** [comment]
> 执行一下命令看一下文件是不是损坏了，预期的 md5 是 14d86ee4893ebbae1b3d4e430a0b15be
> 
> ```
> md5 /Users/william/Documents/rainbow/rainbow-brackets-cracked.jar
> ```

MD5的值是对的

**Comment by gimgoo** [comment]
没用，改了也是一个样

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/31849284/3130ae29-47d8-4927-8ee6-e9688199b622)

vmoptions

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/31849284/54b6302d-5251-42f0-9680-c69e2b27482d)

**Comment by gimgoo** [comment]
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/31849284/7c051b77-be7f-4084-bff9-96a930b9991e)

可能破解的这东西或许不是谁都能用吧，哈哈，可能认人

**Comment by hcliu987** [comment]
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/52879991/ec765f09-c62a-4505-a0a7-23651a1d6b41)
这个样子吗？？？？看样子是有效果了

**Comment by gimgoo** [comment]
> ![image](https://private-user-images.githubusercontent.com/52879991/335802710-ec765f09-c62a-4505-a0a7-23651a1d6b41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDcxNTgsIm5iZiI6MTcxNzI0Njg1OCwicGF0aCI6Ii81Mjg3OTk5MS8zMzU4MDI3MTAtZWM3NjVmMDktYzYyYS00NTA1LWEwYTctMjM2NTFhMWQ2YjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDEzMDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MzExM2I2ODMwNTI2MTU2ZjVkMmFhNmZlODE2YmIzODA0M2IxZWNjZGM0MDZjYjAwYTMxY2ZhMWM4ZTkxNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0_2nhzD9uZdAbJSdW42lfPNM5B7wq-wwPL62kdNb3x4) 这个样子吗？？？？看样子是有效果了

这么看缘分的？我这边就显示红色

**Comment by gimgoo** [comment]
这破解的生效估计有概率一说，我卸载了重装也是这样

**Comment by gimgoo** [comment]
idea.vmoptions文件：

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/31849284/8dbb5ddc-14ef-4fe5-9b8a-7139823ac771)

MD5值校验：
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/31849284/61d3892b-7b7f-4427-a63a-b4ffa6dd739e)

ja-netfilter在这里下载： https://gitee.com/ja-netfilter/ja-netfilter/releases/tag/2022.2.0

最终结果：

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/31849284/7fcd25c6-0e7a-4d32-bef3-c68301320171)

我的配置是没有问题的吧？所以说实锤是概率生效

**Comment by ReaJason** [comment]
我知道为什么不生效了，因为你用了 bin/idea.vmoptions 吧，这个不应该动的，你从 https://3.jetbra.in/ 下一个新的 ja-netfilter 吧，里面有一键脚本会用新的 vmoptions 文件。

**Comment by AkazaAkaria** [comment]
![Clip_2024-06-02_17-48-59](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/80370422/0d1b7d0d-20e8-49b3-840f-5cfeadae7e25)
![Clip_2024-06-02_17-49-42](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/80370422/6e9066cc-c612-4484-b954-397dcb46f90d)
没有破解,怎么处理

**Comment by AkazaAkaria** [comment]
我的依旧破解不了

**Comment by hcliu987** [comment]
> 我知道为什么不生效了，因为你用了 bin/idea.vmoptions 吧，这个不应该动的，你从 https://3.jetbra.in/ 下一个新的 ja-netfilter 吧，里面有一键脚本会用新的 vmoptions 文件。

你试一下这个吧，然后重新配置一下
