### ISSUE TITLE
rainbow-brackets 插件无法使用

### ISSUE THREAD

**Issue by AkazaAkaria** [JAgentSphere/bytebuddy-agent-demo#5]
![Clip_2024-06-03_10-59-23](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/80370422/b030979f-ec4e-42e9-a5c4-c8db58cb2908)
![Clip_2024-06-03_11-01-12](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/80370422/d060b7c1-cb2d-4461-9300-77a9a68c9c25)
可有其他的方式

**Comment by ReaJason** [comment]
需要贴一下 idea64.exe.vmoptions 这个文件的全路径，看是不是 idea 内置的

**Comment by AkazaAkaria** [comment]
![Clip_2024-06-03_18-07-17](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/80370422/4c083cc8-8226-4f34-ba28-de5ff41d1178)
idea下安装的是如图所示的配置![Clip_2024-06-03_18-05-53](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/80370422/bb09cf1c-3b39-4782-b719-70fd1a36875e)
是这个吗

**Comment by vruc** [comment]
为什么会有 active-agt-idea.jar 的，就不怕打架吗

**Comment by AkazaAkaria** [comment]
注释掉啦,但是还是激活不了
