### ISSUE TITLE
还是无法使用呢

### ISSUE THREAD

**Issue by CloverAn** [JAgentSphere/bytebuddy-agent-demo#6]
不知道是不是操作问题。我基于已经激活使用的jetbra，在jetbra的vmoptions - idea.vmoptions增加了javaagent并且在jetbrains之上。已经重启电脑和软件，在idea中看配置也是OK的，但是setting中rainbow-brackets显示检测到使用了ja-netfilter，请问大佬这个怎么解决呢。

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/44476858/451068a6-fd6c-4093-9b90-b73c7219ecb8)
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/44476858/c9d364d5-55ad-4ac5-b2e3-a33d7a1eee6e)

**Comment by ReaJason** [comment]
可以看一下 idea 程序所在的 bin 目录下的 vmoptions 文件是否存在 ja-netfilter 或破解的字符，需要删掉

**Comment by ReaJason** [comment]
<IDE_HOME>\bin\idea64.exe.vmoptions

**Comment by CloverAn** [comment]
也是没有的

![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/44476858/612c0955-773a-4742-bec6-2a0af74991d9)

**Comment by CloverAn** [comment]
另外idea版本是2023.2.5

**Comment by ReaJason** [comment]
嗷嗷，这个版本可能有别的检测，可以参考博客自行破解，我是测试的是 2024 版的插件
