### ISSUE TITLE
已配置文件，插件破解无效

### ISSUE THREAD

**Issue by shiny6667** [JAgentSphere/bytebuddy-agent-demo#8]
大佬还是用不了，两个位置都配置了
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/91005394/f44cafe9-4931-4f1e-99b3-969ff0a93c50)
这个是安装目录
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/91005394/c469c83d-d52f-4c97-ad39-b17703691191)
这个是C盘的文件目录
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/91005394/f7c60bb6-4d50-45da-bd00-aa982547baa1)
能搜索到的只有这两个，剩下的貌似不是
![image](https://github.com/JAgentSphere/bytebuddy-agent-demo/assets/91005394/50b6869e-8f13-4289-9257-9dccf7bf74ac)
结果还是这样，求大佬指点一二

**Comment by suhaoxu** [comment]
![截图_20240730144003](https://github.com/user-attachments/assets/d2f027fb-6816-480d-8fde-d114323d707b)
在idea里面配置就可以了
